### DISCUSSION TITLE
MQTT Publish Commands YAML. - Lock Car & Air Con etc..

### DISCUSSION THREAD

**Discussion by chrisandsally** [tillsteinbach/WeConnect-mqtt#284] [Q&A]
Hi Folks,  I have created a load of MQTT states and templates in Home Assistant to put values on the Dashboards and convert to Miles etc.  

However How do I lock the Car and Turn the AirCon remotely?  I have the S-Pin in the docker compose file.

What do I need to put in here?

'''
service: mqtt.publish
data: {}
'''

Any help appreciated.

**Comment by andlo** [comment]
I use a mqtt switch like this:

`mqtt:
  - switch:
      name: "WeConnect e-up climatisation"
      state_topic: "weconnect/vehicles/WVWZZZXXXXXXXX/domains/climatisation/climatisationStatus/climatisationState"
      command_topic: "weconnect/vehicles/WVWZZZXXXXXXXX/controls/climatisation_writetopic"
      payload_on: "start"
      payload_off: "stop"
      state_on: "heating"
      state_off: "off"`

But a mqtt.publish could als work
Something like this:
`service: mqtt.publish
data:
  topic: weconnect/vehicles/WVWZZZXXXXXXXX/controls/climatisation_writetopic
  payload: start
`

**Reply by chrisandsally** [reply]
Hi @andlo thank you, will give that a try. Thanks. Chris x

**Reply by chrisandsally** [reply]
what payload would it be to remote lock the car? 'start' 'lock' or something else?

**Reply by tillsteinbach** [reply]
it is 'lock' and 'unlock'

**Reply by chrisandsally** [reply]
Thank you!. In order to update HA  after a lock command, what is the payload?.  And how do know these?

Tried this. 

service: mqtt.publish
data:
  topic: weconnect/0/mqtt/weconnectForceUpdate_writetopic
  payload: start (also tried on)

**Reply by tillsteinbach** [reply]
That does not help, because you do not know when you need to update, because the time it takes to send the command to the car is not constant. But it also should not be necessary. After sending the command it should update itself until the command was successful or failed.

**Reply by chrisandsally** [reply]
Ahh, thank you tillsteinbach.

**Reply by janchlebek** [reply]
Hi guys, great project!!! Works like a charm so far :) 
One question though: do you maybe have some documentation on payload values? I am mainly interested in enabling and disabling charging times and adjusting of charging current (I have some automations based on location). 
All the respective writeable topics are visible but I am not sure about the correct payload.

**Reply by nicoferrett** [reply]
Hi, I'm trying to lock and unlock the car but it doesnt't work, climatisation works.
Here is my code:
```
mqtt:
  switch:
    - unique_id: 123zz67890123d
      name: "WeConnect ID3 climatisation"
      state_topic: "weconnect/vehicles/WVWZZZXXXXXX/domains/climatisation/climatisationStatus/climatisationState"   
      command_topic: "weconnect/vehicles/WVWZZZXXXXXX/controls/climatisation_writetopic"
      payload_on: "start"
      payload_off: "stop"
      state_on: "heating"
      state_off: "off"

  lock:     
    - unique_id: 123ab67890123d
      name: "WeConnect ID3 access"
      state_topic: "weconnect/vehicles/WVWZZZXXXXXX/domains/access/accessStatus/doorLockStatus"   
      command_topic: "weconnect/vehicles/WVWZZZXXXXXX/controls/access_writetopic"
      payload_lock: "lock"
      payload_unlock: "unlock"
      state_locked: "locked"
      state_unlocked: "unlocked"
```

Any help appreciated!
