### DISCUSSION TITLE
0.30.0 released

### DISCUSSION THREAD

**Discussion by tillsteinbach** [tillsteinbach/WeConnect-mqtt#94] [Announcements]
### Fixed
- Requests tracking behaviour
- Catch error when token could not be fetched

### Changed
- Requests changed from list to dict

### Added
- Possibility to use temperature when startng climatisation
- Added fail_no_external_power to generic request status
- Added chargeType attribute to chargingStatus
- Added chargingSettings attribute to chargingStatus

<hr /><em>This discussion was created from the release <a href='https://github.com/tillsteinbach/WeConnect-mqtt/releases/tag/v0.30.0'>0.30.0</a>.</em>

**Comment by diplix** [comment]
i like the new requests tracking behaviour. i catch it in home assistant with a mqtt sensor:

```
sensor:
  - platform: mqtt
    state_topic: weconnect/vehicles/+/domains/climatisation/climatisationStatus/request/+/status
    name: weconnect_climate_request_status
    unique_id: EB517498-A4B0-4ACB-9F45-DCD0579D0D9A
    availability_mode: all
    availability:
      - topic: weconnect/mqtt/weconnectConnected
        payload_available: "True"
        payload_not_available: "False"
```
the new _possibility to use temperature when startng climatisation_ raises a problem for me. i set temperature in home assistant with a mqtt hvac device and when i restart home assistant or reload my mqtt settings, the integration sends the temperature to the write topic — which then  triggers the heating in the car.

(it’s the little dots in the screenshot, always at reloads/reatarts set to 19°C)

<img width="1417" alt="Bildschirmfoto 2022-02-25 um 21 01 30" src="https://user-images.githubusercontent.com/4541494/155791727-03e3046c-7710-4bf9-bf41-06aa4bcdc09d.png">

can this new behavior be disabled with a settiing/start option? or could heating the car be only triggered when the temperature changes?
