### ISSUE TITLE
how *domains/charging/chargingSettings/targetSOC_pct in Home Assistant?

### ISSUE THREAD

**Issue by Schnabel80** [tillsteinbach/WeConnect-mqtt#308]
Im Using WeConnect-mqtt to get the Datas in Home Assistant. 
But i don't have an Idee how i can include the target SOC and the Target climate temperature.
Have anyone an idea?

Thanks a lot!

**Comment by wormiedk** [comment]
Here is my configuration if added through configuration.yaml it adds most of the possible values

```
mqtt:
  - image:
    - name: "ID4 car image"
      unique_id: ID.4_car_image
      image_topic: "weconnect/vehicles/CARVIN/pictures/car"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"         
        identifiers:           
          - volkswagen_id4
    - name: "ID4 status image"
      image_topic: "weconnect/vehicles/CARVIN/pictures/status"
      unique_id: ID.4_status_image
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"         
        identifiers:           
          - volkswagen_id4
    - name: "ID4 status image with badge"
      image_topic: "weconnect/vehicles/CARVIN/pictures/statusWithBadge"
      unique_id: ID.4_status_image_wbadge
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"         
        identifiers:           
          - volkswagen_id4
    - name: "ID4 car image with badge"
      image_topic: "weconnect/vehicles/CARVIN/pictures/carWithBadge"
      unique_id: ID.4_car_image_wbadge
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"         
        identifiers:           
          - volkswagen_id4      
    - name: "ID.4 battery level"
      unique_id: ID.4_battery
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/batteryStatus/currentSOC_pct"
      unit_of_measurement: "%"
      device_class: "battery"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"         
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 battery tempereture"
      unique_id: ID.4_battery_temperature
      state_topic: "weconnect/vehicles/CARVIN/domains/measurements/temperatureBatteryStatus/temperatureHvBatteryMax_K"
      unit_of_measurement: "C"
      device_class: "temperature"
      value_template: "{{ value | round(2) - 273.15 }}"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"         
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 range"
      unique_id: ID.4_range
      device_class: "distance"
      state_topic: "weconnect/vehicles/CARVIN/domains/fuelStatus/rangeStatus/primaryEngine/remainingRange_km"
      unit_of_measurement: "km"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 odometer"
      unique_id: ID.4_odometer
      device_class: "distance"
      state_topic: "weconnect/vehicles/CARVIN/domains/measurements/odometerStatus/odometer"
      unit_of_measurement: "km"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 charge time left"
      unique_id: ID.4_chrgtime
      device_class: "duration"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingStatus/remainingChargingTimeToComplete_min"
      unit_of_measurement: "min"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 charge power"
      unique_id: ID.4_charge_power
      device_class: "power"
      unit_of_measurement: "kW"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingStatus/chargePower_kW"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 charge rate"
      unique_id: ID.4_charge_rate
      unit_of_measurement: "km/h"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingStatus/chargeRate_kmph"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 charge type"
      unique_id: ID.4_charge_type
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingStatus/chargeType"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 plug connection"
      unique_id: ID.4_plug_connection
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/plugStatus/plugConnectionState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 plug lock"
      unique_id: ID.4_plug
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/plugStatus/plugLockState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 plug external power"
      unique_id: ID.4_plug_external_power
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/plugStatus/externalPower"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door lock"
      unique_id: ID.4_door
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doorLockStatus"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 access overall"
      unique_id: ID.4_access_overall
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/overallStatus"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door bonnet open"
      unique_id: ID.4_door_bonnet_open
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/bonnet/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door frontLeft lock"
      unique_id: ID.4_door_frontLeft
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/frontLeft/lockState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door frontLeft open"
      unique_id: ID.4_door_frontLeft_open
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/frontLeft/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door frontRight lock"
      unique_id: ID.4_door_frontRight
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/frontRight/lockState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door frontRight open"
      unique_id: ID.4_door_frontRight_open
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/frontRight/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door rearLeft lock"
      unique_id: ID.4_door_rearLeft
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/rearLeft/lockState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door rearLeft open"
      unique_id: ID.4_door_rearLeft_open
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/rearLeft/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door rearRight lock"
      unique_id: ID.4_door_rearRight
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/rearRight/lockState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door rearRight open"
      unique_id: ID.4_door_rearRight_open
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/rearRight/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door trunk lock"
      unique_id: ID.4_door_trunk
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/trunk/lockState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 door trunk open"
      unique_id: ID.4_door_trunk_open
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/doors/trunk/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 window frontLeft"
      unique_id: ID.4_window_frontLeft
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/windows/frontLeft/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 window frontRight"
      unique_id: ID.4_window_vehicles
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/windows/frontRight/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 window rearLeft"
      unique_id: ID.4_window_rearLeft
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/windows/rearLeft/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 window rearRight"
      unique_id: ID.4_window_rearRight
      state_topic: "weconnect/vehicles/CARVIN/domains/access/accessStatus/windows/rearRight/openState"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 parking lat"
      unique_id: ID.4_parking_lat
      state_topic: "weconnect/vehicles/CARVIN/parking/parkingPosition/latitude"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 parking lng"
      unique_id: ID.4_parking_lng
      state_topic: "weconnect/vehicles/CARVIN/parking/parkingPosition/longitude"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 parking time"
      unique_id: ID.4_parking_time
      device_class: "timestamp"
      state_topic: "weconnect/vehicles/CARVIN/parking/parkingPosition/carCapturedTimestamp"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"      
        identifiers:           
          - volkswagen_id4
  - switch:
    - name: "ID.4 charge"
      unique_id: ID.4_charging
      optimistic: true
      command_topic: "weconnect/vehicles/CARVIN/controls/charging_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingStatus/chargingState"
      state_on: "charging"
      state_off: "readyForCharging"
      payload_on: "start"
      payload_off: "stop"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 AC"
      unique_id: ID.4_ac
      optimistic: true
      command_topic: "weconnect/vehicles/CARVIN/controls/climatisation_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationStatus/climatisationState"
      state_on: "heat"
      state_off: "off"
      payload_on: "start"
      payload_off: "stop"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 AC right"
      unique_id: ID.4_ac_right
      optimistic: true
      command_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/zoneFrontRightEnabled_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/zoneFrontRightEnabled"
      state_on: "True"
      state_off: "False"
      payload_on: "true"
      payload_off: "false"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 AC left"
      unique_id: ID.4_ac_left
      optimistic: true
      command_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/zoneFrontLeftEnabled_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/zoneFrontLeftEnabled"
      state_on: "True"
      state_off: "False"
      payload_on: "true"
      payload_off: "false"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 AC on unlock"
      unique_id: ID.4_ac_on_unlock
      optimistic: true
      command_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/climatizationAtUnlock_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/climatizationAtUnlock"
      state_on: "True"
      state_off: "False"
      payload_on: "true"
      payload_off: "false"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
  - number:
    - name: "ID.4 max charge"
      unique_id: ID.4_max_charge
      command_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingSettings/targetSOC_pct_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingSettings/targetSOC_pct"
      min: 0
      max: 100
      step: 1
      unit_of_measurement: "%"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
  - select:
    - name: "ID.4 max charge current"
      unique_id: ID.4_max_charge_current
      command_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingSettings/maxChargeCurrentAC_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingSettings/maxChargeCurrentAC"
      options:
        - "maximum"
        - "reduced"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
```

**Comment by wormiedk** [comment]
Forgot the climatisation temperature

This should be added under number:
```
  - number:
    - name: "ID.4 max charge"
      unique_id: ID.4_max_charge
      command_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingSettings/targetSOC_pct_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/charging/chargingSettings/targetSOC_pct"
      min: 0
      max: 100
      step: 1
      unit_of_measurement: "%"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
    - name: "ID.4 climatisation temp"
      unique_id: ID.4_climatisation_temp
      command_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/targetTemperature_C_writetopic"
      state_topic: "weconnect/vehicles/CARVIN/domains/climatisation/climatisationSettings/targetTemperature_C"
      min: 16
      max: 30
      step: 0.5
      unit_of_measurement: "C"
      device:
        manufacturer: "Volkswagen"
        model: "ID.4"
        identifiers:           
          - volkswagen_id4
```
