### ISSUE TITLE
Bug: username/password commandline parameters are mandatory - no way to use .netrc

### ISSUE THREAD

**Issue by ai91** [tillsteinbach/WeConnect-mqtt#309]
Configuring secrets, but unfortunately it does work for MQTT connection only. User and password for weconnect are mandatory.

Starting with docker. When trying to omit USER/PASSWORD environment variables, the weconnect-mqtt fails with error message `weconnect-mqtt: error: argument -u/--username: expected one argument`

**Configuration:**
docker-compose.yml
```
version: '3.3'

services:
  weconnect-mqtt:
    image: "tillsteinbach/weconnect-mqtt:latest"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LC_ALL=de_DE
      - BROKER_ADDRESS=192.168.1.200
      - ADDITIONAL_PARAMETERS=--netrc /run/secrets/weconnect_netrc
    secrets:
      - weconnect_netrc

secrets:
   weconnect_netrc:
     file: /root/secrets/weconnect_netrc
```

the netrc contains entries for `volkswagen.de`, `myvolkswagen.de`, `vwgroup.io`, `identity.vwgroup.io` - but none is picked.

**Workaround:**
The only solution to make it working, is provide USER/PASSWORD explicitly in docker-compose.yml:
```
version: '3.3'

services:
  weconnect-mqtt:
    image: "tillsteinbach/weconnect-mqtt:latest"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LC_ALL=de_DE
      - BROKER_ADDRESS=192.168.1.200
      - ADDITIONAL_PARAMETERS=--netrc /run/secrets/weconnect_netrc
      - USER=mysecretuser@example.com
      - PASSWORD=mysecretpassword
    secrets:
      - weconnect_netrc

secrets:
   weconnect_netrc:
     file: /root/secrets/weconnect_netrc
```

**TODO:**
make user/password paramethers optional, to allow pick values from `netrc` secret.
