### ISSUE TITLE
oauth2.InsecureTransportError

### ISSUE THREAD

**Issue by astriffe** [tillsteinbach/WeConnect-mqtt#374]
When starting the weconnect-mqtt image with version 0.49.2 (ID d5748de3e9df), I'm getting an error:
`oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.`

My env configurations are as follows: 
```
      env:
        TZ: Europe/Zurich
        LC_ALL: de_CH
        USER: ...
        PASSWORD: ...
        BROKER_ADDRESS: xxx.xxx.xxx.xxx
        ADDITIONAL_PARAMETERS: --interval 600
```
As far as I recognize, the error message describes the oAuth call *to* VW? Is there anything I can do about it myself?
