### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Reinschki** [tillsteinbach/WeConnect-mqtt#81]
Hallo Till,

vielen Dank für diese wunderbare Arbeit!

Ich verwende WeConnect-MQTT im Docker Container und empfange und verarbeite die Daten in Fhem. Funktioniert einwandfrei.
Es geht um einen neuen Tiguan.

Nur das ausliefern der Bilder klappt nicht!?
Hier meine Docker-Compose-Datei:
```
version: '3.3'

services:
  weconnect-mqtt:
    container_name: weconnect-mqtt
    image: "tillsteinbach/weconnect-mqtt:latest"
    restart: unless-stopped
    environment:
      - USER=test@test.de
      - PASSWORD=myvwidpassword
      - BROKER_ADDRESS=192.168.178.80
      - ADDITIONAL_PARAMETERS=-l 50.301051 8.813559 --chargingLocationRadius 500 --pictures --picture-format txt -v
```

Das und viele weitere Variationen habe ich auch schon ausprobiert:

`--picture-format png`

Ich beobachte über MQTT.fx per Subscibe den Kanal weconnect/0/vehicles/WVGZZZ5N??????????/pictures/# und erhalte keine Nachrichten, so dass Fhem natürlich auch nicht empfangen kann.

Hast du einen Tipp für mich?

Viele Grüße
Reiner
